[package]
name = "kernel-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
pathbuf = "1.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
serde_with = "3.14.0"
toml = "0.9.2"
tracing = "0.1.41"
thiserror = "2.0.12"
