# config/kernel.toml
# 内核开启 KEXEC 配置
CONFIG_KEXEC = "y"
CONFIG_KEXEC_FILE = "y"
CONFIG_CRASH_DUMP = "y"
CONFIG_RELOCATABLE = "y"
CONFIG_BLK_DEV_INITRD = "y"
CONFIG_DEVTMPFS = "y"
CONFIG_DEVTMPFS_MOUNT = "y"
CONFIG_DEBUG_INFO = "y"
CONFIG_PROC_VMCORE = "y"
CONFIG_VT = "y"
CONFIG_CONSOLE_TRANSLATIONS = "y"
CONFIG_FB = "y"
CONFIG_SYSFS = "y"
CONFIG_SYSRQ = "y"
CONFIG_KASAN = "y"
CONFIG_KASAN_GENERIC = "y"
CONFIG_KASAN_INLINE = "y"
CONFIG_DEBUG_KMEMLEAK = "y"
CONFIG_MAGIC_SYSRQ = "y"
CONFIG_DEBUG_KMEMLEAK_AUTO_SCAN = "y"
CONFIG_PANIC_ON_OOPS = "y"
CONFIG_BUG = "y"
CONFIG_DEBUG_BUGVERBOSE = "y"
CONFIG_KALLSYMS = "y"
CONFIG_KALLSYMS_ALL = "y"
CONFIG_GDB_SCRIPTS = "y"